import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {ASSET,PROTOCOL,MODEL,REVISION} from '../chatlearn/config.js';
import {sha256,canonical,floatBytes,validateManifest,judge} from '../chatlearn/manifest.js';
import {verifiedModelResponse,installModelBridge} from '../chatlearn/stream.js';
import {createChatLearningApplication} from '../chatlearn/app.js';
function evidence(){return {target:{before:Array(12).fill(3),after:Array(12).fill(2.98)},anchors:{before:Array(12).fill(3),after:Array(12).fill(3)},behavior:Array.from({length:8},(_,i)=>({id:i,beforePass:true,afterPass:true}))};}
async function manifest(){const m={schema:'PINF-CHAT-RELEASE-1',protocol:PROTOCOL,status:'accepted_experimental',model:MODEL,revision:REVISION,device:'wasm',dtype:'q8',asset:ASSET,generation:1,sourceRecordHash:'a'.repeat(64),trainingStatus:'accepted_experimental',values:Array(896).fill(7.5),weightHash:await sha256(floatBytes(Array(896).fill(7.5))),patchedModelHash:'b'.repeat(64),baseChunkHashes:Array(Math.ceil(ASSET.bytes/ASSET.chunkSize)).fill('c'.repeat(64)),patchedChunkHash:'d'.repeat(64),evidence:evidence(),actualOnnxEvaluation:true,measurementRevision:'PINF-CHAT-WASM-EVAL-1'};return {...m,releaseHash:await sha256(canonical(m))};}
test('conversion contract targets verified tensor, not graph or arbitrary paths',()=>{assert.equal(ASSET.offset,17876744);assert.equal(ASSET.length,896*4);assert.equal(ASSET.bytes,512096557);});
test('release requires measured benefit and separate inference evidence',async()=>{assert.equal((await validateManifest(await manifest())).device,'wasm');});
test('rejected and unknown learning never become a chat release',async()=>{for(const status of ['candidate','unknown','rejected'])await assert.rejects(validateManifest({...await manifest(),status}));});
test('post-evaluation weight mutation is rejected',async()=>{const m=await manifest();m.values[0]=7.75;await assert.rejects(validateManifest(m),/WEIGHT_IDENTITY/);});
test('post-evaluation record mutation is rejected',async()=>{const m=await manifest();m.generation=2;await assert.rejects(validateManifest(m),/RELEASE_HASH/);});
test('non-finite, wrong-size and non-float weights fail closed',async()=>{for(const values of [[],Array(896).fill(NaN),Array(896).fill(101)])assert.throws(()=>floatBytes(values));const m=await manifest();m.values[0]=7.500000000000001;m.weightHash=await sha256(floatBytes(m.values));await assert.rejects(validateManifest(m),/NON_FLOAT32/);});
test('arbitrary ONNX revision or offset is denied',async()=>{await assert.rejects(validateManifest({...await manifest(),revision:'main'}));await assert.rejects(validateManifest({...await manifest(),asset:{...ASSET,offset:0}}));});
test('QA regressions cannot be offset by loss gain',()=>{const e=evidence();e.behavior[0].afterPass=false;assert.equal(judge(e).pass,false);});
test('missing runs and false PASS text cannot authorize release',()=>{assert.throws(()=>judge({target:{},behavior:[]}));const e=evidence();e.behavior[0].afterPass='PASS';assert.throws(()=>judge(e));});
test('small statistically visible but subthreshold gain is not adopted',()=>{const e=evidence();e.target.after.fill(2.995);assert.equal(judge(e).pass,false);});
test('anchor loss must satisfy both worst-case and mean constraints',()=>{const e=evidence();e.anchors.after[0]=3.06;assert.equal(judge(e).pass,false);e.anchors.after.fill(3.02);assert.equal(judge(e).pass,false);});
test('a model with poor baseline QA cannot be approved by this gate',()=>{const e=evidence();e.behavior.slice(0,5).forEach(x=>x.beforePass=false);assert.equal(judge(e).pass,false);});
async function fixture(){
 const raw=new Uint8Array(16384);for(let i=0;i<raw.length;i++)raw[i]=i%251;
 const asset={bytes:raw.length,chunkSize:4096,offset:4096+100,length:3584,normHash:await sha256(raw.subarray(4196,7780))};
 const m={values:Array(896).fill(7.5),weightHash:'hash',releaseHash:'release',baseChunkHashes:[]};for(let i=0;i<4;i++)m.baseChunkHashes.push(await sha256(raw.subarray(i*4096,(i+1)*4096)));
 const changed=raw.slice();changed.set(floatBytes(m.values),asset.offset);m.patchedChunkHash=await sha256(changed.subarray(4096,8192));return {raw,changed,m,asset};
}
test('stream changes only trained tensor after authenticating all chunks',async()=>{const {raw,changed,m,asset}=await fixture(),receipt={};const result=new Uint8Array(await verifiedModelResponse(new Response(raw),m,{asset,receipt}).arrayBuffer());assert.deepEqual(result,changed);assert.equal(receipt.applied,true);assert.equal(receipt.verifiedChunks,4);assert.notDeepEqual(raw,changed);});
test('corrupted model cache cannot be silently patched',async()=>{const {raw,m,asset}=await fixture();raw[12000]^=1;const receipt={};await assert.rejects(verifiedModelResponse(new Response(raw),m,{asset,receipt}).arrayBuffer(),/MODEL_CHUNK_HASH/);assert.equal(receipt.applied,false);});
test('truncated download never reports loaded learned weights',async()=>{const {raw,m,asset}=await fixture(),receipt={};await assert.rejects(verifiedModelResponse(new Response(raw.subarray(0,9000)),m,{asset,receipt}).arrayBuffer());assert.equal(receipt.applied,false);});
test('target and patched tensor checksums are independently enforced',async()=>{const {raw,m,asset}=await fixture();await assert.rejects(verifiedModelResponse(new Response(raw),m,{asset:{...asset,normHash:'0'.repeat(64)}}).arrayBuffer(),/ORIGINAL_NORM_HASH/);await assert.rejects(verifiedModelResponse(new Response(raw),{...m,patchedChunkHash:'0'.repeat(64)},{asset}).arrayBuffer(),/PATCHED_CHUNK_HASH/);});
test('fragmented network reads preserve exact output and bounded chunking',async()=>{const {raw,changed,m,asset}=await fixture();let n=0;const s=new ReadableStream({pull(c){if(n>=raw.length)return c.close();c.enqueue(raw.subarray(n,Math.min(n+151,raw.length)));n+=151;}});assert.deepEqual(new Uint8Array(await verifiedModelResponse(new Response(s),m,{asset}).arrayBuffer()),changed);});
test('custom cache installation is reversible and does not poison base ONNX',async()=>{const env={useBrowserCache:true,useCustomCache:false,customCache:null};let puts=0;const restore=installModelBridge(env,{}, {cache:{put:async()=>puts++}});await env.customCache.put(`https://huggingface.co/${MODEL}/resolve/${REVISION}/onnx/model_quantized.onnx`,new Response('patched'));assert.equal(puts,0);restore();assert.deepEqual(env,{useBrowserCache:true,useCustomCache:false,customCache:null});});
test('service serves only an independently checked release and no arbitrary file',async()=>{
 const s=await createChatLearningApplication({factory:()=>http.createServer((req,res)=>{res.writeHead(404);res.end('legacy');}),manifestProvider:manifest});await new Promise(r=>s.listen(0,'127.0.0.1',r));const u='http://127.0.0.1:'+s.address().port;
 try{const r=await fetch(u+'/api/chat-release');assert.equal((await r.json()).status,'accepted_experimental');assert.equal((await fetch(u+'/chatlearn/config.js')).status,200);assert.equal((await fetch(u+'/chatlearn/publish.js')).status,404);}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}
});
test('service access failure preserves an unavailable result, not fabricated approval',async()=>{const s=await createChatLearningApplication({factory:()=>http.createServer((q,r)=>r.end()),manifestProvider:()=>{throw Error('offline');}});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{const x=await(await fetch('http://127.0.0.1:'+s.address().port+'/api/chat-release')).json();assert.equal(x.status,'unavailable');}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}});
import {publicationPlan,publish} from '../chatlearn/publish.js';
async function publication(){const m=await manifest();return {schema:'PINF-CHAT-PUBLICATION-1',attempt:'1',evaluation:{schema:'PINF-CHAT-CANDIDATE-1',status:'completed',decision:'ADOPT_CHAT_EXPERIMENTAL_NORM',runId:'1',baseCommit:'commit',evidence:m.evidence,weightHash:m.weightHash,sourceRecordHash:m.sourceRecordHash},release:m,browser:{status:'passed',mode:'real-model',releaseHash:m.releaseHash,weightHash:m.weightHash,verifiedChunks:m.baseChunkHashes.length,twoTurns:true,reloadVerified:true,rollbackVerified:true,noPaidPost:true}};}
test('publisher refuses mock browser evidence and post-test mutation',async()=>{const r=await publication();r.browser.mode='mock';await assert.rejects(publicationPlan(r),/BROWSER_NOT_VERIFIED/);});
test('failed learning is recorded without installing a model',async()=>{const r=await publication();r.evaluation.decision='REJECT_CHAT_NORM';assert.equal((await publicationPlan(r)).install,false);});
test('writer cannot run without a dedicated credential',async()=>{await assert.rejects(publish(await publication(),{token:''}),/NO_PUBLISH_CREDENTIAL/);});
test('publisher checks actual job origin',async()=>{await assert.rejects(publish(await publication(),{token:'not-a-real-key',runId:'2',commit:'commit',fetcher:()=>{throw Error('should-not-fetch');}}),/WRONG_WORKFLOW/);});
test('all publication checks preserve the measured weight identity',async()=>{const r=await publication();assert.equal((await publicationPlan(r)).manifest.weightHash,r.release.weightHash);});
