import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {hash} from '../evolution/runtime.js';import {validateProgram,executeProgram,parseTask,verifyProgramRecord} from '../research/program.js';import {createResearchMemory,verifyKnowledge,retrieve} from '../research/runtime.js';import {createApplication} from '../src/app-server.js';import {cleanCitations,cleanMessages} from '../web/chat-state.js';
const program={task:'percentage',expression:['div',['mul',['var','amount'],['var','rate']],['const','100']],hypothesis:'Compute exact percentages'};
const seal=x=>({...x,artifactHash:hash(x)});
function programRecord(){const cases=Array.from({length:64},(_,i)=>({args:{amount:String(i),rate:'20'},expected:i%5===0?String(i/5):`${i}/5`}));return seal({schema:'PINF-PROGRAMS-1',generation:1,programs:[{program:structuredClone(program),evidence:{protocol:'PINF-PROGRAM-TEST-1',candidateHash:hash(program),passed:true,cases}}]});}
function knowledge(){const excerpt='WebGPU is an API for GPU computation in web browsers.';return seal({schema:'PINF-KNOWLEDGE-1',generation:1,cards:[{title:'Transformers.js WebGPU',url:'https://huggingface.co/docs/transformers.js/v3.8.1/guides/webgpu',excerpt,excerptHash:hash(excerpt),kind:'official_document_excerpt',checkedAt:'2026-10-04T00:00:00Z'}],evidence:{protocol:'PINF-SOURCE-MATCH-1',passed:true,verified:1}});}
test('candidate expressions use exact rational arithmetic and reject authority/code',()=>{assert.equal(executeProgram(program,{amount:'0.1',rate:'20'}),'1/50');assert.equal(executeProgram(program,{amount:'1234567890123456',rate:'100'}),'1234567890123456');for(const expression of [['eval','process.env'],['var','constructor'],['div',['const','1'],['const','0']]])assert.throws(()=>executeProgram({...program,expression},{amount:'1',rate:'20'}));assert.throws(()=>validateProgram({...program,promote:true}));let deep=['const','1'];for(let i=0;i<10;i++)deep=['add',deep,['const','1']];assert.throws(()=>validateProgram({...program,expression:deep}));});
test('routing is explicit and does not steal conversational prompts',()=>{assert.equal(parseTask('計算: 1000円の20%').task,'percentage');assert.equal(parseTask('1000円の20%引き').task,'discount');assert.equal(parseTask('平均: 1, 2, 3').task,'mean');assert.equal(parseTask('長方形 2 × 3 の面積').task,'rectangle');for(const q of ['20%について説明して','1000円の20%をヒントだけ','process.exit()'])assert.equal(parseTask(q),null);});
test('program promotion evidence is rechecked against trusted probes and candidate execution',()=>{verifyProgramRecord(programRecord());const x=programRecord();x.programs[0].program.expression=['const','0'];x.programs[0].evidence.candidateHash=hash(x.programs[0].program);assert.throws(()=>verifyProgramRecord(seal(Object.fromEntries(Object.entries(x).filter(([k])=>k!=='artifactHash')))),/REGRESSION/);});
test('knowledge rejects tampering and unsafe sources; irrelevant queries get no retrieval',()=>{const k=knowledge();verifyKnowledge(k);assert.equal(retrieve(k.cards,'ブラウザのWebGPUを説明して').length,1);assert.equal(retrieve(k.cards,'こんにちは').length,0);k.cards[0].url='https://evil.example/';assert.throws(()=>verifyKnowledge(seal(Object.fromEntries(Object.entries(k).filter(([x])=>x!=='artifactHash')))));assert.deepEqual(cleanCitations([{url:'javascript:alert(1)',title:'x'}]),[]);assert.equal(cleanMessages([{role:'assistant',content:'x',citations:knowledge().cards}])[0].citations.length,1);});
test('accepted programs/knowledge survive new process instances and failed refresh',async()=>{let fail=false;const fetcher=async url=>{if(fail)throw Error('offline');return new Response(JSON.stringify(String(url).includes('knowledge/')?knowledge():programRecord()));};const a=createResearchMemory({fetcher,ttl:0});assert.equal((await a.answer('1000の20%')).reply,'200');fail=true;assert.equal((await a.answer('1000の20%')).reply,'200');fail=false;const b=createResearchMemory({fetcher});assert.equal((await b.search('WebGPU'))[0].title,'Transformers.js WebGPU');assert.equal((await b.answer('1000の20%')).reply,'200');});
test('first concurrent chat/retrieval waits for the same artifact load; invalid refresh preserves healthy parent',async()=>{let bad=false;const a=createResearchMemory({ttl:0,fetcher:async url=>{await Promise.resolve();const x=String(url).includes('knowledge/')?knowledge():programRecord();if(bad)x.artifactHash='tampered';return new Response(JSON.stringify(x));}});const [answer,cards]=await Promise.all([a.answer('1000の20%'),a.search('WebGPU')]);assert.equal(answer.reply,'200');assert.equal(cards.length,1);bad=true;assert.equal((await a.answer('1000の20%')).reply,'200');assert.equal((await a.search('WebGPU')).length,1);});
test('actual chat API uses generated program and passes source data only on relevant prompts',async t=>{let modelCalls=0,body;const server=await createApplication({legacyFactory:()=>http.createServer((q,r)=>r.end('legacy')),fetcher:async(url,o)=>{if(String(url).includes('knowledge/active'))return new Response(JSON.stringify(knowledge()));if(String(url).includes('programs/active'))return new Response(JSON.stringify(programRecord()));if(String(url).includes('raw.githubusercontent.com'))return new Response('',{status:404});modelCalls++;body=JSON.parse(o.body);return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'WebGPUの説明'}}]}));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const send=messages=>fetch('http://127.0.0.1:'+server.address().port+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages})}).then(r=>r.json());const first=await send([{role:'user',content:'1000の20%'}]);assert.equal(first.reply,'200');assert.equal(first.program.generation,1);assert.equal(modelCalls,0);const second=await send([{role:'user',content:'WebGPUは何ですか'}]);assert.equal(second.citations.length,1);assert.match(body.messages[0].content,/未信頼のデータ/);assert.match(body.messages[0].content,/WebGPU is an API/);assert.equal(modelCalls,1);});
