const $=id=>document.getElementById(id);
const KEY='pinf-remote-chat-v1';let messages=[],busy=false,controller=null;
try{const a=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(a))messages=a.filter(m=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string').slice(-20);}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(messages.slice(-20)));}catch{}}
function render(){const list=$('messages');list.replaceChildren();for(const m of messages){const el=document.createElement('div');el.className='message '+m.role;const role=document.createElement('span');role.className='role';role.textContent=m.role==='user'?'あなた':'Project ∞';el.append(role,document.createTextNode(m.content));list.append(el);}$('empty').hidden=messages.length>0;}
function controls(){const text=$('input').value.trim();$('send').disabled=busy||!text;$('send').textContent=busy?'回答中…':'送信';$('stop').hidden=!busy;}
function prompt(){const recent=messages.slice(-8).map(m=>(m.role==='user'?'ユーザー: ':'AI: ')+m.content.slice(0,1500)).join('\n');return '以下の会話に日本語で簡潔かつ正確に回答してください。事実と不確実性を区別してください。\n\n'+recent+'\nAI:';}
async function ask(){if(busy)return;const text=$('input').value.trim();if(!text)return;messages.push({role:'user',content:text});$('input').value='';save();render();busy=true;controls();$('error').textContent='';$('progress').textContent='回答を生成しています…';controller=new AbortController();
 try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:messages.slice(-8)}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(60000)])});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();const reply=String(data.reply||'').trim();if(!reply)throw Error('空の応答');messages.push({role:'assistant',content:reply});save();$('progress').textContent='';}
 catch(e){$('error').textContent=e?.name==='AbortError'?'停止しました。':'回答に失敗しました。もう一度送信してください。';$('progress').textContent='';}
 finally{busy=false;controller=null;controls();render();$('scroll').scrollTop=$('scroll').scrollHeight;}}
$('form').onsubmit=e=>{e.preventDefault();ask();};$('stop').onclick=()=>controller?.abort();
$('input').oninput=()=>{const e=$('input');e.style.height='auto';e.style.height=Math.min(120,e.scrollHeight)+'px';controls();};
$('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229&&!matchMedia('(pointer: coarse)').matches){e.preventDefault();$('form').requestSubmit();}};
$('new').onclick=()=>{controller?.abort();messages=[];busy=false;$('input').value='';$('error').textContent='';$('progress').textContent='';save();render();controls();$('notice').textContent='新しい会話にしました。';};
function date(s){const d=new Date(s);return Number.isFinite(d.getTime())?d.toLocaleString('ja-JP'):'時刻不明';}
const trigger=e=>e==='schedule'?'定刻による実行':e==='push'?'コード更新後の実行':e==='workflow_dispatch'?'手動で開始した実行':e||'未確認';
async function research(){const dialog=$('research-dialog');$('refresh').disabled=true;$('research').textContent='記録を取得しています…';const urls=['/api/free/status','/api/autonomy/status','/api/runtime/status'];const data=await Promise.all(urls.map(async url=>{try{const r=await fetch(url,{signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}catch{return {available:false};}}));const a=data[0].research,b=data[1],c=data[2];const lines=[];lines.push('① 過去の部分学習実験',a?.available?date(a.at)+'\n採用判定：'+(a.learningDecision||'未確認'):'記録を取得できませんでした。');lines.push('\n② 研究用モデルの継承',b?.available?date(b.at)+'\n'+trigger(b.event)+'／研究世代 '+b.generationBefore+' → '+b.generationAfter:'記録を取得できませんでした。');lines.push('\n③ 起動・復旧コードの変更',c?.available?date(c.at)+'\n'+trigger(c.event)+'\n'+(c.applied?'限定コードの反映記録あり。':'今回のコード反映なし。'):'記録を取得できませんでした。');$('research').textContent=lines.join('\n');$('research-raw').textContent=JSON.stringify(data,null,2);$('refresh').disabled=false;}
$('records').onclick=()=>{$('research-dialog').showModal();research();};$('close-records').onclick=()=>$('research-dialog').close();$('refresh').onclick=research;
if(window.visualViewport){const fit=()=>{document.body.style.height=Math.round(window.visualViewport.height)+'px';};window.visualViewport.addEventListener('resize',fit);fit();}
render();controls();